version: "2"
linters:
  enable:
    - cyclop
    - goconst
    - gocritic
    - gosec
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .+_test.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .+_test.go
      - third_party$
      - builtin$
      - examples$
